"""add advanced_rag_enabled field to chatbot

Revision ID: 64314f8aacab
Revises: 
Create Date: 2025-05-01 12:25:04.407387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64314f8aacab'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###  <-- Or manually written
    op.add_column('chatbot', sa.Column('advanced_rag_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))
    # Note: Added nullable=False and server_default=sa.false()
    # Adjust if you want it to be nullable or have a different default.
    # server_default=sa.false() works well for adding non-nullable booleans to existing tables.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ### <-- Or manually written
    op.drop_column('chatbot', 'advanced_rag_enabled')
    # ### end Alembic commands ###